### ISSUE TITLE
undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by arkrost** [robertgzr/homebrew-tap#1]
It seems that [this](https://github.com/robertgzr/homebrew-tap/commit/0f49ccf8f617608fdf10d32cd94be7762a9ac70e) commit introduces error.

```
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/robertgzr/homebrew-tap/iosevka.rb:149:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:140:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1095:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:552:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1090:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:552:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by bijn** [comment]
Ran into this error as well. Seems like the formula is accessing null variables.
In case anyone is having trouble, this seemed to fix it for me:
<img width="412" alt="iosevka-tap" src="https://user-images.githubusercontent.com/2113032/37479085-feecc306-2838-11e8-93d7-211a25fbe2a2.png">

**Comment by cryptism** [comment]
@bijn looks good, but shouldn't that second change be `preset << ligset unless ligset == nil?`?
